export * as session from './session/events'
export * as democracy from './democracy/events'
export * as council from './council/events'
export * as technicalCommittee from './technical-committee/events'
export * as phragmenElection from './phragmen-election/events'
export * as preimage from './preimage/events'
export * as referenda from './referenda/events'
